source/properties.rst
=> properties.rst

source/hessian.rst
added documentation related to: https://github.com/grimme-lab/xtb/pull/22
=> closes #12

source/contents.rst, source/development.rst, source/setup.rst
=> update setup and installation guide

source/contents.rst
See http://cuby4.molecular.cz/interface_xtb.html
=> Add cuby4 as framework supporting xtb

source/contents.rst, source/geometry.rst, source/sp.rst, source/xcontrol.rst
Information on all supported geometry input formats, extensions and limitations to those.
=> Add guide to geometry formats supported in xtb

source/contents.rst, source/geometry.rst, source/xtb_info.rst, source/xtb_thermo.rst, source/xtb_topo.rst
=> Add documentation regarding submodules

source/commandline.rst, source/xcontrol.rst
=> Add links to man pages

source/contents.rst
supports xTB since 7.4
fixes #27
=> Add link to Turbomole

source/hessian.rst, source/xtbrelatedrefs.rst
=> Adding SPH calculations to xtbdocs

source/crestcmd.rst, source/crestxmpl.rst
I updated the layout by introducing tabs in the CREST examples and fixed some typos.
=> update of the layout

source/qcxms_doc/qcxms_plot.rst
Update for PlotMs Version 6.0
- includes exact mass description
- add flag *-p* and *-i* for intensities
=> update version 6.0

source/community/index.rst, source/community/pyvibms.rst
use PyVibMS to visualize the vibrational analysis result by xtb
=> add pyvibms support

source/community/index.rst, source/community/scine.rst
Almost completely adapted from the README from the wrapper repository.
=> Adds SCINE wrapper to the community page

README.rst, source/qcxms_doc/qcxms.rst, source/qcxms_doc/qcxms_cites.rst, source/qcxms_doc/qcxms_ex.rst, source/qcxms_doc/qcxms_plot.rst, source/qcxms_doc/qcxms_run.rst, source/qcxms_doc/qcxms_setup.rst
Updated descriptions for QCxMS for the latest major release version.
=> QCxMS v.5.2.0 update

source/qcxms_doc/qcxms_plot.rst, source/qcxms_doc/qcxms_setup.rst
Moved **.mass_raw.agr** desciption to correct destination in _qcxms_plot.rst_
=> corrected plotms descriptions

source/contents.rst, source/xtb_ir.rst
Signed-off-by: Julia Kohn <jkohn@thch.uni-bonn.de>
=> IR submodule description

source/xtb_docking.rst
Signed-off-by: cplett <82893466+cplett@users.noreply.github.com>
=> Adding aISS citation

source/oniom.rst
if external charges are specified, one has to be careful with charges
=> Explanation for charges

source/setup.rst
make the content tree version-independent
=> update the content of tarball

source/oniom.rst
add some consistent description of the charges
=> clarify --chrg for ONIOM

source/requirements.txt
fix the `.. tabbed::`  directive
=> Update requirements.txt to be version independent

source/capi.rst
Very minor but rather eye catching.
=> MAINT: Minor typo

source/CENSO_docs/censo.rst, source/CENSO_docs/censo_extensive_keywords.rst, source/CENSO_docs/censo_implementation.rst, source/CENSO_docs/censo_nmr.rst, source/CENSO_docs/censo_parallel.rst, source/CENSO_docs/censorc.rst
* updated implementation section
* removed mentions of removed features
* updated hints
=> Update for CENSO 2.1.3
